version: '3.7'

services:
  geophotobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geophotobot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./admins.json:/bot/admins.json
      - ./allowed_users.json:/bot/allowed_users.json
